### ISSUE TITLE
🐛 BUG:Inconsistent member name formats in clip search dialog

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#130]
The names populating the member select dropdown in the clip search dialog currently follow an inconsistent format, e.g. '兎咲 ミミ', '英リサ', '夜乃くろむ / Yano Kuromu'.
For consistency's sake, I would love to see the format standardized (perhaps to either '[名字] [名前]' or '[名字][名前]' — most names currently appear to follow the latter).

<img width="305" alt="spodule-search-dialog-inconsistent-member-names-1" src="https://github.com/sugar-cat7/vspo-portal/assets/155891765/93369154-2ef4-4593-87ac-a547c17d62ca">

**Comment by sugar-cat7** [comment]
I agree.

Also, currently, the names and other details are retrieved from hard-coded files, which is not an ideal approach. Eventually, I would like to switch to fetching this information from an API.
