### ISSUE TITLE
🐛 BUG:Bottom nav state inconsistent with current page/route

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#131]
Performing page navigation through any means aside from the bottom nav, e.g. via the sida nav or the browser's back button, makes the state of the bottom nav (i.e. the highlighted button) inconsistent with the current page.

For instance,
1. clicking 切り抜き in the bottom nav brings the user to `/clips` and 切り抜き is correctly highlighted; then
2. clicking 配信一覧 in the bottom nav brings the user to `/schedule/all` and 配信一覧 is correctly highlighted; then however
3. clicking the browser's back button brings the user back to `/clips` but **配信一覧 incorrectly remains highlighted** when we expect the highlight to switch back to 切り抜き.

More fundamentally, it might be nice if we could agree upon what the state of the bottom nav should actually reflect.
When casually using the website myself, my initial assumptions with the bottom nav were that:
- clicking on 配信一覧 would always open `/schedule/all`, but it would be highlighted on any page under `/schedule` (since to me, `/schedule/live`, `/schedule/[yyyy-mm-dd]`, etc. simply felt like different filters applied to `/schedule/all`);
- clicking on 切り抜き would always open `/clips` and 切り抜き would only be highlighted on `/clips`;
- clicking on クリップ would always open `/twitch-clips` and クリップ would only be highlighted on `/twitch-clips`;
- clicking on イベント would always open `/events/[current yyyy-mm]` and イベント would be highlighted on any page under `/events` (i.e. `/events/[yyyy-mm]` and `/events/details/[id]`); and
- no button in the nav bar would be highlighted on any other page (e.g. `/about`).

Would this behaviour be reasonable, or do you suggest we do something else? @sugar-cat7 

Also, afaict `/freechat` is the only page on the site which does not show the bottom nav.
Was this intentional? or would you say it should probably appear there too? (I think I would prefer it to be there for consistency's sake 🙂)

https://github.com/sugar-cat7/vspo-portal/assets/155891765/f522407b-d5f5-49d1-89d6-4e09d76229eb

**Comment by sugar-cat7** [comment]
Your approach to the highlighting method seems good :)

Also, the absence of the bottom nav on /freechat is an oversight in implementation.
