### ISSUE TITLE
📎 Refactor `/data` files

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#132]
I believe there is some opportunity for cleanup here.
Some things which I would like to see addressed:
- Inconsistent usage of types: Some consts are typed while others are not (some of which types are available for). I would especially like for mock data to be typed with the same types as those used in our API calls.
- Inconsistent variable names: Inconsistent usage of `mock` prefix; inconsistent capitalization of words like `LiveStream` and `KeyWord`.
- Inconsistent file types: It feels strange and unnecessary having a mix of `ts`, `js`, and `jsx` here (especially `jsx` since there seems to be no HTML markup involved). Most files are currently `js`, so in order to make use of types it would probably make sense to switch to `ts` (or to annotate with JSDoc).
- Duplicated data: Consts like `members` and `memberKeyWords` feel susceptible to diversion — perhaps they could be unified or have some sort of single source of truth.

This list is not exhaustive; please feel free to edit or add any points related to `/data` which are not listed.
I can also try raising a PR some time this week addressing the above, and perhaps we can work off there to see what else might warrant refactoring.

**Comment by sugar-cat7** [comment]
I agree. Eventually, we plan to automatically generate types from the OpenAPI generated by the Backend service, but since that is still some way off, I welcome refactoring as a temporary solution.
