### ISSUE TITLE
🐛 BUG:Hide chat tab on Twitch VODs

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#133]
When viewing a Twitch VOD in the `LivestreamDetailsModal`, the chat tab is available in the tab panel for the user to open.
Because this embedded chat is the live chat from that member's Twitch channel (and **not** the VOD's archived chat), having this chat tab can be especially confusing when viewing a VOD of a member who is currently streaming on Twitch.

The tab panel already hides the chat tab for YouTube VODs, so we should probably do the same for Twitch.

https://github.com/sugar-cat7/vspo-portal/assets/155891765/270823ab-1192-47b6-a0cc-207e36b01a2d

**Comment by sugar-cat7** [comment]
I agree.
