### ISSUE TITLE
🚀 Feature Request:Auto-select user's preferred color scheme on initial load

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#134]
I propose that we follow the common pattern of auto-selecting the user's light/dark mode preference on first load using the `prefers-color-scheme` media query. This may help dark mode users feel more welcome when first visiting the website.
I see this as a small change which simply checks the media query if a theme is not yet set in `localStorage`. The order of priority would thus be `localStorage` > `prefers-color-scheme` > app default.

Many websites nowadays also seem to have a 'use system default' option in their theme picker which makes the site track changes to `prefers-color-scheme`, matching the user's device when it switches between light and dark mode (e.g. depending on the time of day).
This functionality is outside the scope of what I had intended for this issue (especially since it would require changing the current light/dark mode toggle button), but if there is value in the feature then I would very much be interested in implementing it.

**Comment by sugar-cat7** [comment]
That sounds good.
This might also help with the flickering issue mentioned here: https://github.com/sugar-cat7/vspo-portal/issues/33
