### ISSUE TITLE
📎 Task: Revisit SEO strategy for drawer contents

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#147]
### Description

We currently include two instances of `CustomDrawer` in the DOM: one which is contained in an MUI `SwipeableDrawer` component and is visible to the user, and another which is set to `display: none`.
My understanding is that we need the latter because the former is invisible to crawlers. (It seems `SwipeableDrawer` uses React Portals under the hood (https://mui.com/material-ui/react-drawer/#keep-mounted, https://mui.com/material-ui/react-modal/#server-side-modal) which is unable to be rendered on the server (https://github.com/facebook/react/issues/13097, https://github.com/reactjs/react-modal/issues/112).

However, I noticed that [MUI suggests](https://mui.com/material-ui/react-modal/#server-side-modal) using the `disablePortal` prop for rendering modals on the server.
I would like to switch to this approach to avoid having to use our own workaround.

Below is what this looks like when disabling browser JS to try to view only the SSRed portion of the page.

Current method with duplicate `CustomDrawer`s
https://github.com/sugar-cat7/vspo-portal/assets/155891765/351843eb-dbbd-460c-a866-424ca15210b8

Proposed method with `disablePortal=true`
https://github.com/sugar-cat7/vspo-portal/assets/155891765/62df5616-7b21-4c0c-8943-99b548912f17

I am not very knowledgeable in SEO, so I would like someone to confirm whether this test actually shows that the drawer contents would be visible to crawlers.

**Comment by sugar-cat7** [comment]
Oh, thank you so much!
This seems really valuable as it eliminates code duplication and makes it worth switching. I noticed that others facing the same issue with Drawer's SSR have resolved it in a similar manner using `MenuProps={{keepMounted:true, disablePortal: true}}`.
https://github.com/mui/material-ui/issues/28643#issuecomment-1481817762

However, it's difficult to measure how much this would affect SEO... 🤔

**Comment by sugar-cat7** [comment]
I may have communicated poorly.
From the perspective of a crawler, I believe there's no impact due to this improvement.
Therefore, I think it's a valuable improvement for us developers to make the code easier to understand.

> do you happen to remember the reason for adding the hidden drawer with display: none?

As you said, this was added to make subpaths visible to the crawler, making it easier for the crawler to discover the page contents.
