### ISSUE TITLE
🐛 BUG: Theme toggle has confusing click area

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#164]
### What operating system are you using?

Mac

### Describe the Bug

The theme toggle button does not register clicks near its periphery, especially on the right side (see clip).
This is annoying/confusing since (1) the cursor changing to a pointer 👆 on hover, (2) the button area turning grey on hover, and (3) the ripple animation playing on click all indicate to the user that the button should be clickable in that spot.
I expect these indicators to align with the actual click area which performs the theme toggle action.

https://github.com/sugar-cat7/vspo-portal/assets/155891765/d952a3ac-e339-4d37-a4ff-3dc621bcbccc

(Afaik this is the only button on the site with this behaviour.)

**Comment by ss77995ss** [comment]
Hi! May I take this one? Looks like the click behavior only asssign to the inner `<label>` tag.
<img width="414" alt="Screenshot 2024-02-13 at 02 41 04" src="https://github.com/sugar-cat7/vspo-portal/assets/28031139/27dc2930-99e4-48a8-a911-224f0a822b02">
