### ISSUE TITLE
🐛 BUG: Some labelled buttons are not rectangular

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#165]
### What operating system are you using?

Mac

### Describe the Bug

Some labelled buttons on the site are completely oval in shape.
I believe this was not intended since this is not a pattern I have seen elsewhere. Buttons with labels are almost always rectangular, hence that is what I expect from these buttons as well.

Below are the two buttons I noticed, though there may be more.

<img width="104" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/155891765/4d6e71c0-4786-49a8-b5e5-055bf9e310c0">

戻る button in LivestreamDetailsModal

https://github.com/sugar-cat7/vspo-portal/assets/155891765/a403927c-3985-4ddf-b202-6672a206c916

設定 button in side nav

**Comment by sugar-cat7** [comment]
This is not intentional. Let's make it a rectangle.

**Comment by ss77995ss** [comment]
I'll take this one. Will also try to check all the labelled buttons in the website
