### ISSUE TITLE
🐛 BUG: Confusing disabled state in events page month selector

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#166]
### What operating system are you using?

Mac

### Describe the Bug

On the events page, the 前の月へ and 次の月へ buttons are clickable even when the button cannot retrieve events from that month.
I expect the buttons to be disabled in these cases.

Furthermore, in light mode, the month selector itself almost looks disabled at first glance due to its light shade of grey.
I believe a darker shade would help avoid potential confusion.

https://github.com/sugar-cat7/vspo-portal/assets/155891765/129cb1f3-bb8f-4dc0-b4c7-599175cc2484

**Comment by sugar-cat7** [comment]
I agree. Furthermore, in the case of the disabled state, I would like to remove the animations when hovering and clicking.

<img width="1109" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/69241625/578a6bd1-3c31-41d1-82de-7e86604288d1">
