### ISSUE TITLE
📎 Increase reliance on ContentLayout

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#174]
### Description

Two main changes I would like to make to increase consistency between pages.
1. Pages currently set their own one-off `padding-top`/`margin-top`s to account for the app header. I would like to move this to the ContentLayout so pages don't have to worry about the app header.
2. Should `/terms` and `/privacy-policy` also show the bottom nav? If so, I feel it would make sense to also move the bottom nav into the ContentLayout. (Even if not, I think I would still prefer moving it and adding something like an optional `hideBottomNavigation` prop for the pages which don't need it.)

**Comment by sugar-cat7** [comment]
I agree with both 1 and 2. It would also be good to add a bottom navigation to the terms and privacy policy.

**Comment by sugar-cat7** [comment]
Thank you for the suggestion! Indeed, the differing screen widths in the drilldown page pairs are quite concerning. Proceeding in this manner should be fine!

(However, currently, the parent elements under the main tag that make up the Page are a mix of Container, Box, or just plain div tags, with no consistency whatsoever. It might be better to unify the page structure based on MUI's layout first before changing the max width specification....🫠 )

**Comment by sugar-cat7** [comment]
I also think using Container is a good idea. In particular, I think using `<Container component="main"> ` as you've shown in the example is great because it avoids inserting unnecessary div.
