### ISSUE TITLE
📎 Add lint rules for potentially problematic MUI import paths

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#194]
### Description

Several MUI import paths that an IDE might suggest/autocomplete are potentially problematic.
This is a suggestion to prevent such imports via linting. (ESLint's `no-restricted-imports` could probably do the job.)

1. [MUI mentions](https://mui.com/material-ui/guides/minimizing-bundle-size/#development-environment) importing icons from `@mui/icons-material` could slow down app startup during development. We could force the dev to import from the path of the specific icon (e.g. `@mui/icons-material/Info`).
2. The `styled` function from `@mui/system` is [missing certain properties](https://github.com/mui/material-ui/issues/30678#issuecomment-1371759159), so we should make sure the import is from `@mui/material/styles`.
3. Imports three levels deep are [considered private](https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports) by MUI.

**Comment by sugar-cat7** [comment]
I agree!

This is unrelated, but regarding point 1, does it seem like we will eventually stop using top-level named imports and start using default imports for each individual MUI component? 👀
