### ISSUE TITLE
📎 Move custom colors into MUI palette

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#195]
### Description

We currently have quite a few hardcoded hex values throughout the codebase.
I believe moving as many of these into the palette object could
- help reduce duplication and
- provide an opportunity to give appropriate and meaningful names to colors. (E.g. we currently use MUI's error color as the color to highlight trending videos — this semantic disconnect can be confusing to follow.)

[This page](https://mui.com/material-ui/experimental-api/css-theme-variables/customization/#adding-new-theme-tokens) looks like it could help with implementing this change.

**Comment by ss77995ss** [comment]
Agree, could also avoid typo
