### ISSUE TITLE
🐛 BUG: Cannot scroll page when cursor is placed along left edge

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#197]
### What operating system are you using?

Mac

### Describe the Bug

On scrollable pages, I am unable to scroll with my trackpad when I place my cursor within ~20px from the left edge of the page.
I believe this is caused by MUI's `SwipeableDrawer` placing an element along the left edge which handles swipe behavior.

Visually, the content that scrolls is the content between the header and the bottom nav, so as a user I expect the page to be scrollable as long as I leave my cursor within this area during the scroll action.

https://github.com/sugar-cat7/vspo-portal/assets/155891765/37aa66b8-49f1-46a0-aa91-0b49c8435fd6

**Comment by sugar-cat7** [comment]
Does this approach likely involve removing the swipeable element of the SwipeableDrawer? Is it possible to keep the swipe functionality while allowing content to scroll?

**Comment by sugar-cat7** [comment]
Indeed, thank you. It does seem to work as expected on the MUI page. 

I haven't tried it, but it looks like adjusting the `swipeAreaWidth` might solve the issue. 
https://v5-0-6.mui.com/pt/api/swipeable-drawer/
