### ISSUE TITLE
🐛 BUG: Video audio continues to play after opening related video

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#203]
### What operating system are you using?

Mac

### Describe the Bug

The LivestreamDetailsModal continues to play audio from the previous video even after the user opens a new video via the related videos tab.

Steps to reproduce:
1. Open and play any stream or clip with audio.
2. Without pausing the video, click on a related video from the related videos tab.

I expect the audio from the previous video to be inaudible once the modal opens the next video.

More specifically, I believe a fix for this problem should take into account the user flow where a user opens and plays a video, opens a related video, then clicks 戻る to return to the first video.
In this flow, I expect either of the two following behaviors:
1. Video `v1` pauses but its state is stored when the user opens a related video `v2`.
If the user opens `v2` when `v1` has a timestamp of 01:23:45, then when the user returns from `v2` to `v1`, `v1` is shown to the user paused at the same timestamp 01:23:45.
2. The state of `v1` is simply lost when the user opens `v2`.
Regardless of the timestamp `v1` has when the user opens `v2`, when the user returns from `v2` to `v1`, `v1` is reloaded from 00:00:00.

My preference as a user is definitely option 1 as long as there is no big hit to performance.

**Comment by sugar-cat7** [comment]
I think 1 is good too.
