### ISSUE TITLE
📎 Improve usage and naming consistency of `fetchEntities` functions

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#205]
### Description

1. Error handling: In `[yearMonth].tsx`, the `fetchVspoEvents` call is wrapped in a try–catch. Elsewhere, the pattern seems to be for these errors to be left unhandled, presumably because Next.js can handle them for us (and because that seems to be the pattern used in their docs).
I suggest we get rid of this try–catch to align with the existing pattern.

2. Naming: Some functions use the `Vspo` prefix on the fetched entity while others don't.
I am in favor of removing this prefix wherever possible. (Even if the `VspoEvent` type cannot be renamed to `Event` due to the naming conflict with JS's `Event`, I prefer that the fetch function be called `fetchEvents` since it is usually clear from context that `VspoEvents` are being fetched.)
<img width="228" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/155891765/cdc61ee8-5654-455a-a69b-bdb7ffa0faa2">

3. `getStaticProps` in `twitch-clips.tsx` contains logic to fetch Twitch clips.
This code looks like it should belong to `api.ts`.
<img width="687" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/155891765/ce7804f8-f18d-4b3f-9b9d-7bd6e7d83dd5">

**Comment by sugar-cat7** [comment]
I agree with 1 to 3.
