### ISSUE TITLE
📎 Standardize splitting of compound word-like names

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#206]
### Description

I would like to standardize the splitting/capitalization of these names.
Throughout the codebase, should we treat these as one word or two?
1. `freechat` vs `free chat`
We mostly treat this as two words (around 14 `freechat`s vs 32 `freeChat`s when searching the project).
2. `livestream` vs `live stream`
We mostly treat this as one word (around 107+ `livestream`s vs 14 `liveStream`s).

There may be more such words, but these are the ones that have bothered me most. 🥲

For 1, I have no strong opinion but slightly prefer `freechat` since when compared, `free chat` sounds to me like a type of chat rather than a type of stream.
For 2, I am strongly in favor of `livestream` since `live stream` sounds more like a stream that is currently live, which in our use case is not true — a `livestream` can be an archive or upcoming as well.

**Comment by sugar-cat7** [comment]
Let's treat both as one word! (`freechat`, `livestream`)
Honestly, I wasn't confident about the nuances in the finer details when it's in English, so this is helpful.
