### ISSUE TITLE
🐛 BUG: Livestream card border/shadow visible through sides of date tab bar

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#213]
### What operating system are you using?

Mac

### Describe the Bug

In light mode, the date tab bar on `/schedule/*` has a solid background but at its sides shows the border/shadow of the cards beneath it.
I could not confirm this bug in dark mode.

Steps to reproduce:
1. Open `/schedule/*`, e.g. `/schedule/all`.
2. Scroll down until the date tab bar overlaps with a livestream card. The left edge of the leftmost card should be visible through the tab bar (see below).

https://github.com/sugar-cat7/vspo-portal/assets/155891765/cfa21104-7145-47eb-9c18-730bd9031ba9

I expect none of the borders or shadows of cards to be visible from the sides of the date tab bar.

**Comment by ss77995ss** [comment]
I can take this one
