### ISSUE TITLE
🐛 BUG: Inconsistent URL detection and malformed links in video description

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#218]
### What operating system are you using?

Mac

### Describe the Bug

In the LivestreamDetailsModal video description, some valid URLs are not turned into links ~~while some links lead to invalid URLs~~.

1. If a URL comes after some text on a line (i.e. if it is not at the start of the line in the original YouTube description), it is not turned into a clickable link.
This inconsistency feels strange as a user, and it is inconvenient when I have to copy the unlinked URL to open the page.
As a user, I expect either for all URLs to be clickable links (ideal) or for none of the URLs to be links (not ideal but better than the current implementation).
<img width="320" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/155891765/1dce3756-49da-4163-9e11-7993f81d348d">

2. ~~Some invalid URLs are turned into links, particularly when the URL is truncated with an ellipsis. For example, the truncated link in the screenshot below leads to `https://www.dospara.co.jp/5gamepc/cts...`.
As a user, I expect either for the truncated URL to be linked to the original untruncated URL (ideal) or for the truncated URL to simply not be clickable.
If the YouTube API is returning the truncated URL, I suppose we have to go with the second option though…~~
No bug here (see comments below)
<img width="360" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/155891765/19177dd7-cfa9-4b00-88e3-464bae6df6d9">

**Comment by sugar-cat7** [comment]
1. If possible, I'd like to make all URLs clickable.

2. Regarding the second point, I checked YouTube, and it seems that the issue is not on our end, but rather the description on the other party's side seems to be incorrect. 🫠

Youtube
<img width="425" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/69241625/5ceb62d0-ef7d-4fd4-8081-7f8440b3cd94">

Youtube API

<img width="1121" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/69241625/8ef3092f-058c-4245-b78b-c7a9d5f9d6ac">

**Comment by sugar-cat7** [comment]
To be honest, I haven't come up with anything other than writing regular expressions myself, and I find it difficult to determine sequences of characters... (It's easy to distinguish boundaries in Japanese, but it seems like boundaries would become unclear in English.)

However, looking at responses from multiple YouTube APIs, I've noticed that a newline character (`\n`) or a space seems to be included after URLs.
So, considering a string that starts with `https:` and includes up to a newline character or a space as a URL might be a practical solution. 🫠
