### ISSUE TITLE
📎 Suggestion: Convert enums to string unions

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#219]
### Description

Switching our usage of string enums to string union types may offer better developer experience, as string enums in TS cannot be compared against string literals.

For instance, a variable typed as `Platform` fails TS's type check when assigned the string "youtube" despite the fact that `Platform.YouTube` has the value `"youtube"`.
<img width="570" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/155891765/fce2b6a9-eca7-4093-bb55-8e8aa201482f">

This behavior can be inconvenient, and this has caused some [ugly type assertions](https://github.com/sugar-cat7/vspo-portal/pull/215#discussion_r1498562678).

This sort of issue would not be present with string literals:
<img width="567" alt="image" src="https://github.com/sugar-cat7/vspo-portal/assets/155891765/6c34d555-a196-4bb8-973a-8649385e31b5">

I am favor of making this change given the site of usage has strong enough typing to properly fail when an incorrect string literal is provided by the developer.

**Comment by sugar-cat7** [comment]
I agree.
Let's change the Enum to a Union type.
