### ISSUE TITLE
📎 Remove livestream search functionality

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#220]
### Description

I noticed the SearchDialog has some unused code that supports the searching/filtering of livestreams.
If this feature is not planned to be used, I would like to remove it to simplify the component.

**Comment by sugar-cat7** [comment]
You can delete it as it's not being used at the moment🙏.

(Incidentally, it was originally possible to search for Livestreams as well, but after stopping client-side paging, it became necessary to call the API every time a search was made, so it was temporarily removed.)

**Comment by sugar-cat7** [comment]
There are no plans to restore it right now, so it's okay to delete it. 🙏
