### ISSUE TITLE
🐛 BUG: Google ad console error on soft navigation

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#241]
### What operating system are you using?

Mac

### Describe the Bug

On the live site, navigating from any page to another seems to log an error to the web console stating that an ad is trying to be inserted into an element which already contains an ad in it.

https://github.com/sugar-cat7/vspo-portal/assets/155891765/d3d074ed-1a1e-4a52-b229-2feb6a1feee3

I expect no error to be logged, however I am unsure as to what behavior should be expected.

This error seems to be caused by the following lines in `GoogleAd.tsx` (specifically the `push()` call):
```tsx
const pathname = usePathname();
useEffect(() => {
  try {
    // eslint-disable-next-line
    ((window as any).adsbygoogle = (window as any).adsbygoogle || []).push(
      {},
    );
  } catch (error) {
    console.error(error);
  }
}, [pathname]);
```
Because the `push` fails (see log), the current behavior is that the ad never changes: the ad stays the same until the user performs a hard navigation (refresh or re-open the site elsewhere).
However, the `pathname` dependency in `useEffect` suggests that the original intent may have been to switch the ad on every path change.
Which behavior is preferable as a fix for this issue? @sugar-cat7 

### Please provide any relevant error logs

```
_app-5cd6971b279c8bd5.js?__WB_REVISION__=5cd6971b279c8bd5:116 TagError: adsbygoogle.push() error: All 'ins' elements in the DOM with class=adsbygoogle already have ads in them.
    at Qp (adsbygoogle.js?client=ca-pub-7433484160229921:221:210)
    at Fp (adsbygoogle.js?client=ca-pub-7433484160229921:217:450)
    at Bp.e.client (adsbygoogle.js?client=ca-pub-7433484160229921:211:43)
    at Ae.ea (adsbygoogle.js?client=ca-pub-7433484160229921:53:239)
    at bj (adsbygoogle.js?client=ca-pub-7433484160229921:87:19)
    at Bp (adsbygoogle.js?client=ca-pub-7433484160229921:211:31)
    at Object.push (adsbygoogle.js?client=ca-pub-7433484160229921:228:150)
    at _app-5cd6971b279c8bd5.js?__WB_REVISION__=5cd6971b279c8bd5:116:3328
    at uU (framework-fda0a023b274c574.js?__WB_REVISION__=fda0a023b274c574:9:84105)
    at oV (framework-fda0a023b274c574.js?__WB_REVISION__=fda0a023b274c574:9:113151)
```

**Comment by sugar-cat7** [comment]
Thank you.

As you mentioned, we were trying to change the advertisements for each path, but currently, the ads are not being purged appropriately, and it seems that reinsertion is not possible.
If possible, I would like to be able to change the advertisements for each page.(However, if this causes the advertisement scripts to reload and significantly increases the page transition time, I would like to avoid it.)
