### ISSUE TITLE
📎 Extract ClipCard from ClipList

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#250]
### Description

We have a LivestreamCard component separate from Livestreams, so I feel it would be natural to break up ClipList (which is currently responsible for both the collection and the individual items) into ClipList and ClipCard.

The main benefit I see (apart from making ClipList more cohesive) is that since there seem to be many similarities between ClipCard and LivestreamCard, it may then be possible to refactor the cards to reduce duplicated code between the two (e.g. general card styling, label on card).

**Comment by sugar-cat7** [comment]
@sruenwg 
> Is this label intentionally set to have a different shade of red from the border?

It is not intentional (a design or implementation mistake). Therefore, I believe it's fine to unify the colors.

> In dark mode, should clip cards use the same shade of gray as livestream cards? or is the darker shade intentional?

This should also be the same component, so I think it is fine to unify the colors with the livestream card.
