### ISSUE TITLE
📎 Settle on consistent name for notification/notice

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#252]
### Description

Since we are inconsistent in how we refer to this, I would like to settle on a single way to refer to what we currently call a *notification*/*notice*.

I am personally a fan of neither since, at least to me,
- a notification is something that is delivered to the user (think app/device notification), and
- a notice is something that is less about the method of delivery and is more about the content itself — 'a message which is meant for everyone to read/hear'.

I feel our notifications/notices are neither of the above: we do not deliver the message to each user, nor do we really intend for everyone to read the notification/notice contents (IMO it is more like supplementary info).

To the best of my knowledge, most other apps/websites refer to this as something like 'site updates', 'site news', 'changelog', or 'release notes'.
I would love it if we could adopt one of these more commonly used names.

Closing this ticket requires renaming all instances of 'notifications'/'notification' and 'notices'/'notice' to ~~whatever name we settle on~~ ['site news'](https://github.com/sugar-cat7/vspo-portal/issues/252#issuecomment-1978667215)/'site news item'.

**Comment by sugar-cat7** [comment]
> it is more like supplementary info

Absolutely, I agree with you.

In addition to updates on the site's features and bug fixes, there is also a slight promotional aspect to related services (like Discord Bots), so perhaps "site news" would be appropriate?
