### ISSUE TITLE
🐛 BUG: Scroll position is shared across all pages

### ISSUE THREAD

**Issue by sruenwg** [sugar-cat7/vspo-portal#263]
### What operating system are you using?

Mac

### Describe the Bug

The site seems to share a single scroll position across all pages.
This means that even pages which the user opens for the first time may load with the page scrolled mid-way down. I believe this is not the intended behavior.

### Navigating to a new page

Steps:
1. Open some scrollable page, e.g. `/freechat`. Let this page be called page A.
2. Scroll down $x$ pixels, where $0 < x < \texttt{maxScrollHeight}(\texttt{pageA})$.
3. Click on some other scrollable page B, e.g. `/notifications`, using site navigation.

#### Observed
Step 3 opens page B scrolled down by $x$ pixels (or, if $x > \texttt{maxScrollHeight}(\texttt{pageB})$, by $\texttt{maxScrollHeight}(\texttt{pageB})$ pixels).

#### Expected
The navigation opens page B at the top, scrolled down by 0 pixels.

### Navigating with browser history

Scroll position is currently also shared between pages when using browser navigation (back, forward, etc.)
Continuing from step 3 above:

4. Scroll page B to the top.
5. Click on page A via site navigation. For clarity, I will refer to this as A2 and the previous instance of page A as A1.
6. Scroll down $y$ pixels, where $0 < y < \texttt{maxScrollHeight}(\texttt{pageA})$ and $y \neq x$ (might be easier to test if $y$ is very different from $x$).
7. Click browser back (to open page B).
8. Click browser forward (to open page A2).
9. Directly navigate to page A1 from two pages earlier via browser history.

#### Observed
Steps 7, 8, & 9 all open the page scrolled down by $y$ pixels (since scroll position is kept from step 6).

#### Expected
I am unsure and am open to discussion as to what behavior we want, but I think the most common pattern is to have the scroll position saved for each instance of each page: step 7 should have scroll position 0, step 8 should have scroll position $y$, and step 9 should have scroll position $x$.
Alternatively, each page (not each *instance* of each page) could save and use its last scroll position, or if neither of the above options work then we could even reset each page's scroll position to 0 on browser history navigation.

I am opposed to creating a fully custom solution for this, as I expect there to be something in Next.js or MUI to help make this work.
My suggestion would be to first try out Next.js's experimental `scrollRestoration` flag since it was noted as a potential solution in a [very relevant issue](https://github.com/vercel/next.js/issues/28778#issuecomment-1330614905) — if its behavior seems reasonable and not unpleasant/jarring to use as a user, then I would like to simply rely on that and go with whatever specific behavior that comes with that flag.

**Comment by sugar-cat7** [comment]
I agree.

Trying out `scrollRestoration` first might be a good idea.

Indeed, having the scroll position shared across all pages feels odd.

For navigation through history, it seems sensible to restore the state (scroll position) of the page after the transition to how it was when it was last interacted with. For a new page (a new instance), setting the position to 0 seems like a good approach.

**Comment by sugar-cat7** [comment]
@sruenwg 
Thank you for the suggestion!
I can accept the proposed CSS change number 1! I think it is fine to prioritize the one that works correctly with window.scrollTo 🙆 (Fortunately, the scrollbar on iOS is subtle and not very noticeable).
