### ISSUE TITLE
🐛 BUG: Error on change day to today only

### ISSUE THREAD

**Issue by Luuckyy** [sugar-cat7/vspo-portal#497]
### What operating system are you using?

Windows

### Describe the Bug

https://github.com/user-attachments/assets/1583543c-111a-45d5-90fb-622e7ecaa46d

## OS / Browser
Using Windows 11 with Brave and Ublock

## Description
There seems to be a problem occuring with a promise rejection which lead to a 404. For some reason it doesn't happen when you go through schedule/all but does when you go through schedule/{today}. Seems to be because it could find any params in the schedule

## How to reproduce
- Open https://www.vspo-schedule.com/
- Click on any day to see the schedule
- Click on today's date (the one you landed on when you open https://www.vspo-schedule.com/ )

### Please provide any relevant error logs

Request : GET https://www.vspo-schedule.com/_next/data/82I110a6-nkanr4TdgiRe/ja/schedule/2024-07-31.json?status=2024-07-31
Response: Status 404 Not Found, data: {"notFound":true}

**Comment by sugar-cat7** [comment]
Sometimes the ISR build fails, probably due to a timeout.

For now, we are progressing with the migration to SSR in the background, which should resolve the issue.🫠

**Comment by Luuckyy** [comment]
Oh so that's why, thanks for the explanation
